"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var authController_js_1 = require("../controllers/authController.js");
var protectRoute_js_1 = require("../middlewares/protectRoute.js");
var authRouter = express_1.default.Router();
authRouter.post("/login", authController_js_1.login);
authRouter.post("/signup", authController_js_1.signup);
authRouter.get("/me", protectRoute_js_1.protectRoute, authController_js_1.getMe);
exports.default = authRouter;
